-- Каноническая аналитическая модель Retail Experimentation Platform.
-- DDL идемпотентен и не зависит от фактических имён колонок raw-файлов.

CREATE TABLE IF NOT EXISTS analytics.dim_customer (
    customer_id text PRIMARY KEY,
    age double precision,
    gender text,
    total_spend numeric(20, 4),
    avg_check numeric(20, 4),
    median_check numeric(20, 4),
    max_check numeric(20, 4),
    transactions_count bigint,
    purchase_frequency double precision,
    days_since_last_purchase double precision,
    unique_products bigint,
    unique_categories bigint,
    favorite_category text,
    avg_discount double precision,
    discounted_purchase_share double precision,
    recency_score smallint,
    frequency_score smallint,
    monetary_score smallint,
    rfm_segment text,
    spending_quantile smallint,
    purchase_frequency_quantile smallint,
    loaded_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_dim_customer_age CHECK (age IS NULL OR age >= 0),
    CONSTRAINT ck_dim_customer_scores CHECK (
        (recency_score IS NULL OR recency_score BETWEEN 1 AND 5)
        AND (frequency_score IS NULL OR frequency_score BETWEEN 1 AND 5)
        AND (monetary_score IS NULL OR monetary_score BETWEEN 1 AND 5)
    )
);

CREATE TABLE IF NOT EXISTS analytics.dim_product (
    product_id text PRIMARY KEY,
    category text,
    loaded_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS analytics.dim_date (
    date_key integer PRIMARY KEY,
    full_date date NOT NULL UNIQUE,
    calendar_year smallint NOT NULL,
    calendar_quarter smallint NOT NULL CHECK (calendar_quarter BETWEEN 1 AND 4),
    calendar_month smallint NOT NULL CHECK (calendar_month BETWEEN 1 AND 12),
    month_name text NOT NULL,
    day_of_month smallint NOT NULL CHECK (day_of_month BETWEEN 1 AND 31),
    iso_week smallint NOT NULL CHECK (iso_week BETWEEN 1 AND 53),
    day_of_week smallint NOT NULL CHECK (day_of_week BETWEEN 1 AND 7),
    day_name text NOT NULL,
    is_weekend boolean NOT NULL
);

CREATE TABLE IF NOT EXISTS analytics.dim_experiment (
    experiment_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    experiment_name text NOT NULL UNIQUE,
    experiment_start timestamptz,
    expected_treatment_share double precision NOT NULL DEFAULT 0.5,
    description text,
    loaded_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT ck_dim_experiment_share CHECK (
        expected_treatment_share > 0 AND expected_treatment_share < 1
    )
);

CREATE TABLE IF NOT EXISTS analytics.fact_purchases (
    purchase_key bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    transaction_id text NOT NULL,
    customer_id text NOT NULL REFERENCES analytics.dim_customer(customer_id),
    product_id text REFERENCES analytics.dim_product(product_id),
    date_key integer NOT NULL REFERENCES analytics.dim_date(date_key),
    purchase_datetime timestamptz NOT NULL,
    amount numeric(20, 4) NOT NULL,
    regular_amount numeric(20, 4),
    loaded_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS analytics.fact_experiment (
    experiment_key bigint NOT NULL REFERENCES analytics.dim_experiment(experiment_key),
    customer_id text NOT NULL REFERENCES analytics.dim_customer(customer_id),
    treatment smallint NOT NULL CHECK (treatment IN (0, 1)),
    target smallint NOT NULL CHECK (target IN (0, 1)),
    loaded_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (experiment_key, customer_id)
);

CREATE TABLE IF NOT EXISTS analytics.experiment_results (
    experiment_key bigint PRIMARY KEY REFERENCES analytics.dim_experiment(experiment_key),
    control_size bigint NOT NULL CHECK (control_size > 0),
    treatment_size bigint NOT NULL CHECK (treatment_size > 0),
    control_conversions bigint NOT NULL CHECK (control_conversions BETWEEN 0 AND control_size),
    treatment_conversions bigint NOT NULL CHECK (treatment_conversions BETWEEN 0 AND treatment_size),
    control_cr double precision NOT NULL CHECK (control_cr BETWEEN 0 AND 1),
    treatment_cr double precision NOT NULL CHECK (treatment_cr BETWEEN 0 AND 1),
    absolute_uplift double precision NOT NULL,
    relative_uplift double precision,
    standard_error double precision NOT NULL,
    z_statistic double precision NOT NULL,
    p_value double precision NOT NULL CHECK (p_value BETWEEN 0 AND 1),
    ci_lower double precision NOT NULL,
    ci_upper double precision NOT NULL,
    effect_size double precision NOT NULL,
    achieved_power double precision NOT NULL CHECK (achieved_power BETWEEN 0 AND 1),
    required_total_size bigint,
    mde_absolute double precision,
    alpha double precision NOT NULL CHECK (alpha > 0 AND alpha < 1),
    statistically_significant boolean NOT NULL,
    calculated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS analytics.experiment_validation_summary (
    experiment_key bigint PRIMARY KEY REFERENCES analytics.dim_experiment(experiment_key),
    observed_control bigint,
    observed_treatment bigint,
    expected_control double precision,
    expected_treatment double precision,
    srm_chi_square double precision,
    srm_p_value double precision CHECK (srm_p_value BETWEEN 0 AND 1),
    srm_detected boolean,
    aa_simulations integer,
    aa_false_positive_rate double precision,
    aa_mean_p_value double precision,
    aa_ks_uniform_p_value double precision,
    bootstrap_iterations integer,
    observed_uplift double precision,
    bootstrap_mean_uplift double precision,
    bootstrap_median_uplift double precision,
    bootstrap_ci_lower double precision,
    bootstrap_ci_upper double precision,
    calculated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS analytics.segment_experiment_results (
    experiment_key bigint NOT NULL REFERENCES analytics.dim_experiment(experiment_key),
    dimension text NOT NULL,
    segment text NOT NULL,
    control_size bigint NOT NULL,
    treatment_size bigint NOT NULL,
    control_cr double precision NOT NULL,
    treatment_cr double precision NOT NULL,
    absolute_uplift double precision NOT NULL,
    relative_uplift double precision,
    ci_lower double precision NOT NULL,
    ci_upper double precision NOT NULL,
    p_value double precision NOT NULL,
    adjusted_p_value double precision NOT NULL,
    significant_adjusted boolean NOT NULL,
    PRIMARY KEY (experiment_key, dimension, segment)
);

CREATE TABLE IF NOT EXISTS analytics.uplift_model_results (
    experiment_key bigint NOT NULL REFERENCES analytics.dim_experiment(experiment_key),
    model_name text NOT NULL,
    train_customers bigint NOT NULL,
    holdout_customers bigint NOT NULL,
    auuc double precision NOT NULL,
    qini_coefficient double precision NOT NULL,
    overall_observed_uplift double precision NOT NULL,
    final_incremental_purchases double precision NOT NULL,
    random_state integer NOT NULL,
    calculated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (experiment_key, model_name)
);

CREATE TABLE IF NOT EXISTS analytics.uplift_predictions (
    experiment_key bigint NOT NULL REFERENCES analytics.dim_experiment(experiment_key),
    customer_id text NOT NULL REFERENCES analytics.dim_customer(customer_id),
    model_name text NOT NULL,
    probability_control double precision NOT NULL CHECK (probability_control BETWEEN 0 AND 1),
    probability_treatment double precision NOT NULL CHECK (probability_treatment BETWEEN 0 AND 1),
    predicted_uplift double precision NOT NULL,
    scored_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (experiment_key, customer_id, model_name)
);

CREATE TABLE IF NOT EXISTS analytics.uplift_deciles (
    experiment_key bigint NOT NULL REFERENCES analytics.dim_experiment(experiment_key),
    model_name text NOT NULL,
    decile smallint NOT NULL CHECK (decile > 0),
    customers bigint NOT NULL,
    control_size bigint NOT NULL,
    treatment_size bigint NOT NULL,
    avg_predicted_uplift double precision NOT NULL,
    treatment_cr double precision,
    control_cr double precision,
    observed_uplift double precision,
    incremental_purchases double precision,
    cumulative_incremental_purchases double precision,
    PRIMARY KEY (experiment_key, model_name, decile)
);

CREATE TABLE IF NOT EXISTS analytics.business_scenarios (
    experiment_key bigint NOT NULL REFERENCES analytics.dim_experiment(experiment_key),
    model_name text NOT NULL,
    scenario_name text NOT NULL,
    strategy text NOT NULL,
    customers_total bigint NOT NULL,
    customers_targeted bigint NOT NULL,
    target_share double precision NOT NULL,
    targeting_threshold double precision,
    communication_cost numeric(20, 4) NOT NULL,
    profit_per_conversion numeric(20, 4) NOT NULL,
    marketing_cost numeric(20, 4) NOT NULL,
    incremental_conversions double precision NOT NULL,
    incremental_value numeric(20, 4) NOT NULL,
    incremental_profit numeric(20, 4) NOT NULL,
    roi double precision,
    scenario_analysis boolean NOT NULL DEFAULT true,
    calculated_at timestamptz NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (experiment_key, model_name, scenario_name)
);

CREATE INDEX IF NOT EXISTS ix_fact_purchases_customer_date
    ON analytics.fact_purchases (customer_id, date_key);
CREATE INDEX IF NOT EXISTS ix_fact_purchases_product
    ON analytics.fact_purchases (product_id) WHERE product_id IS NOT NULL;
CREATE INDEX IF NOT EXISTS ix_fact_purchases_datetime
    ON analytics.fact_purchases (purchase_datetime);
CREATE INDEX IF NOT EXISTS ix_fact_experiment_treatment_target
    ON analytics.fact_experiment (experiment_key, treatment, target);
CREATE INDEX IF NOT EXISTS ix_segment_results_dimension
    ON analytics.segment_experiment_results (experiment_key, dimension);
CREATE INDEX IF NOT EXISTS ix_uplift_predictions_model_score
    ON analytics.uplift_predictions (experiment_key, model_name, predicted_uplift DESC);
CREATE INDEX IF NOT EXISTS ix_business_scenarios_profit
    ON analytics.business_scenarios (experiment_key, model_name, incremental_profit DESC);
